### ISSUE TITLE
Homework-1 Issues

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [Smanneni/epam-js-training#1]
1. Put homework's in a separate folders.
2. Use proper indents and spaces in the code

Get Middle Character
a) Recommended to use single 'return' inside a function.
b) (inputstring.length / 2) this expression has to be assigned to variable and use that variable.

Rental Car Costs
a) (Noofdays*parseInt(DialyCarRent.slice(1))) -- parseInt is not requires (ex- 4*'5' gives 20) and is calculation is repetative. So, we can assign this expression to a variable and use that.
b) Use single var pattern, instead of declaring var on each variable declaration.

Modify these task as suggested, let me know if you need any other details.

**Comment by Smanneni** [comment]
@maheshbhuvanagiri   
Implemented the review comments .

**Comment by maheshbhuvanagiri** [comment]
GetMiddleCharacter
a. (stringLength / 2) is still duplicating, could you refactor that code block.

**Comment by Smanneni** [comment]
Implemented the above comment.

**Comment by maheshbhuvanagiri** [comment]
@Smanneni 
All the tasks looks good
