### ISSUE TITLE
HW 2

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [Smanneni/epam-js-training#3]
@Smanneni 

**Calculatewithfunction**

1. This below block of code is repatetive in all the functions from zero to nine , only the function name 
    and number (0-9) are varying in these function. Make a separate function take these number (0-9) as 
    input and return a function (use closure).

   function **zero**(operator) {
     return operator ? operator **(0) : 0**;
  }

**Chainaddingfunction**

1. Not recommneded to end function declaration with ";" , use ";" to end a statements (variable 
   declaration,  variable assignments, function expressions)

**Functionwithinfunction**

1. Test cases are failing, make sure all the code blocks in this examples are passing the test cases. one function is enough for this assignment.

**Comment by Smanneni** [comment]
@maheshbhuvanagiri 

Updated with the review comments.

**Comment by maheshbhuvanagiri** [comment]
user single var pattern, in Calculatewithfunction, FunctionComposition
ex: var s= "abc",
           y= "def",
           z= "ghi";

**Comment by Smanneni** [comment]
@maheshbhuvanagiri 

updated with review comments.please verify.

**Comment by maheshbhuvanagiri** [comment]
Changes looks good
