### ISSUE TITLE
HW-3

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [Smanneni/epam-js-training#4]
@Smanneni 

**array-helpers**
1. No need of new array inside every function and a for loop, you can use array function `map`, `filter' to 
    loop over array elements.

**Comment by Smanneni** [comment]
@maheshbhuvanagiri 

Updated with review comments.

**Comment by maheshbhuvanagiri** [comment]
@Smanneni 
**new with Apply.**
1. The objective of this example is to avoid using `new` , and use create a object.
    use `object.create` and apply to set the arguments to newly created object from the passed argument

please the read the details in the codewars exercise.

**using-closures-to-share-class-state**
1. I couldn't see the exception handling the code.
2. totalWeight -= weight - w;  this needs to be corrected.

lets correct the changes till here

**Comment by Smanneni** [comment]
@maheshbhuvanagiri 

Updated with review comments.please go through it.

**Comment by maheshbhuvanagiri** [comment]
changes looks good, but follow proper indents and spaces
